server:
  port: 8111

logging:
  config: classpath:log/logback-boot.xml


spring:
    application:
      name: service-helloworld
    profiles:
      active: local
feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath*:mapping/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


---
spring:
  profiles: local
  datasource:
          url: jdbc:mysql://127.0.0.1:3306/cfy?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8110/eureka/
query:
  all: a