server:
  port: 8110

logging:
  config: classpath:log/logback-boot.xml

spring:
  profiles:
    active: local
  zipkin:
      base-url: http://localhost:11008
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: service-center
# ��������ʹ��ip���ʵ����
    prefer-ip-address: true

---

spring:
  profiles: local
  application:
    name: service-center-local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8110/eureka/